wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.19.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740030119
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      - 105
      2:
      - 1
      - 41
      - 50
      - 55
      - 105
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.8.19
      5: 0.19.6
      8:
      - 5
      13: linux-x86_64
mlp:
  desc: null
  value:
    hidden_dim: 256
    activation: relu
    dropout: 0.1
    batch_norm: true
train:
  desc: null
  value: {}
run_name:
  desc: null
  value: null
wandb:
  desc: null
  value:
    log: true
    project_name: bilevel
    entity: zjzwin
    resume: false
    tags: null
rseed:
  desc: null
  value: 99
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.01
optimization:
  desc: null
  value:
    lambda_aux: 0.2
    ema_decay: 0.05
optimization.ema_decay:
  desc: null
  value: 0.01736521468143146
optimization.lambda_aux:
  desc: null
  value: 0.211303524434226
